name: 'snowflake_workshop'
version: '1.0.0'
config-version: 2

profile: 'default'
vars:
  surrogate_key_treat_nulls_as_empty_strings: True
  id_amt: 1479650

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests/"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  
clean-targets:         
    - "target"
    - "dbt_modules"
# on-run-start: "insert into PC_DBT_DB.DBT_NTHATIPALLI.users (id,name) values(900,'svjdsjv') "
# on-run-end: "insert into PC_DBT_DB.DBT_NTHATIPALLI.users (id) values(1000)  "

models:
  pre-hook : "insert into PC_DBT_DB.DBT_NTHATIPALLI.users (id) values(9000)"
  snowflake_workshop:
    staging:
      materialized: view
      snowflake_warehouse: pc_dbt_wh
    marts:
      materialized: table
      snowflake_warehouse: pc_dbt_wh_large